config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :events

  root 'pages#index'
  post 'micropost/:id' => 'events#postcreate' , as: 'microposts'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
# == Schema Information
#
# Table name: camps
#
#  id         :integer          not null, primary key
#  course_id  :integer
#  item_id    :integer
#  name       :string(255)      not null
#  condition  :text(65535)
#  deleted_at :datetime
#  created_at :datetime
#  updated_at :datetime
#  dojo_id    :integer
#

class Event < ActiveRecord::Base
  has_many :microposts
  validates :name ,presence: true
  validates :deadline ,presence: true
  validates :place ,presence: true
end

app/models/micropost.rb
# == Schema Information
#
# Table name: camps
#
#  id         :integer          not null, primary key
#  course_id  :integer
#  item_id    :integer
#  name       :string(255)      not null
#  condition  :text(65535)
#  deleted_at :datetime
#  created_at :datetime
#  updated_at :datetime
#  dojo_id    :integer
#


class Micropost < ActiveRecord::Base
  belongs_to :event
  validates :content ,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #jpmobile
  include Jpmobile::ViewSelector

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :postcreate]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  # showでmicropostのnewも行っている
  def show
    @micropost = @event.microposts.build
    #   redirect_to @event
    # else
    #   redirect_to @event
    # end
  end

  def postcreate
    @micropost = @event.microposts.build(post_params)
    if @micropost.editor.blank?
      @micropost.editor = '名無しの権兵衛'
    end
    if @micropost.save
      redirect_to @event
    else
      redirect_to @event
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.save!
    redirect_to @event
    rescue
      flash.now[:danger] = '必須な項目が入力されていません'
      render 'new'
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :deadline, :place, :comment, :info, :event_type)
    end
    def post_params
      params.require(:micropost).permit(:content, :event_id, :created_at, :editor)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@reports = []
  	@tests = []
    @events = []
    @others = []
  	for i in 0..6 do
  		@events += Event.where(deadline: Date.today+i)
  	end

    @events.each do |event|
      if event.event_type == 'レポート'
        @reports.push(event)
      elsif event.event_type == '小テスト'
        @tests.push(event)
      else
        @others.push(event)
      end
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/_form.html.erb
<div>
  <div class="form-horizontal" role="form">
    <%= form_for(@event) do |f| %>
      <div class="field form-group">
        <%= f.label :name,:class => "col-sm-3 control-label" %><br>
        <div class="col-sm-7">
        <%= f.text_field :name, :class => "form-control" %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :deadline,:class => "col-sm-3 control-label" %><br>
        <div class="col-sm-7">
         <%= f.date_field :deadline, :class => "form-control" %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :event_type,:class => "col-sm-3 control-label" %><br>
        <div class="col-sm-7">
          <%= f.select :event_type, ['レポート','小テスト','テスト','その他'], { include_blank: '選択してください' }, class: "form-control" %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :place,:class => "col-sm-3 control-label" %><br>
        <div class="col-sm-7">
          <%= f.text_field :place, :class => "form-control" %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :comment,:class => "col-sm-3 control-label" %><br>
        <div class="col-sm-7">
          <%= f.text_area :comment, :class => "form-control" %>
        </div>
      </div>


      <div class="actions form-group">
        <div class="col-sm-offset-3 col-sm-10">
          <%= f.submit "送信", :class => "btn btn-primary"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_form_smart_phone.html.erb
<div>
  <div rsole="form">
    <%= form_for(@event) do |f| %>
        <%= f.label :name,:class => "control-label"%>
        <div class="form-field">
        <%= f.text_field :name, :class => "form-control" %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :deadline,:class => "control-label" %>
        <div class="form-field">
         <%= f.date_field :deadline, :class => "form-control" %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :event_type,:class => "control-label" %>
        <div class="form-field">
          <%= f.select :event_type, ['レポート','小テスト','テスト','その他'], { include_blank: '選択してください' }, class: "form-control" %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :place,:class => "control-label" %>
        <div class="form-field">
          <%= f.text_field :place, :class => "form-control" %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :comment,:class => "control-label" %>
        <div class="form-field">
          <%= f.text_area :comment, :class => "form-control" %>
        </div>
      </div>
      <div class="align-center">
          <%= f.submit "送信", :class => "button"%>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_navi_smart_phone.html.erb
<div class="header">
<h1><%=  link_to 'Applied Physics', root_path, 'data-no-turbolink' => true %></h1>
<div class="dropmenu">
<ul class="dropdown">
<li><a class="dropdown-toggle" data-toggle="dropdown" href="/">MENU<b class="caret"></b></a>
    <ul class="dropdown-menu bullet pull-right">
      <li><%= link_to '情報一覧', events_path, 'data-no-turbolink' => true%></li>
      <li><%= link_to '新規登録', new_event_path,'data-no-turbolink' => true%></li>
      <li><%= link_to 'お問い合わせ', 'https://twitter.com/applied_w'%></li>
      <li><%= link_to 'トップに戻る', root_path,'data-no-turbolink' => true%></li>
    </ul>
</li>
</ul>
</div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div id="calendar"></div>

app/views/events/index_smart_phone.html.erb
<%= render 'navi'%>
<div id="calendar" data-no-turbolink></div>

app/views/events/new.html.slim
.container.center-block.new
  h1 Add New Info
  = render 'form'
  = link_to 'Back', events_path,'data-no-turbolink' => true

app/views/events/new_smart_phone.html.erb
<div class="dropmenu">
<ul class="dropdown">
<li><a class="dropdown-toggle" data-toggle="dropdown" href="#">MENU<b class="caret"></b></a>
    <ul class="dropdown-menu bullet pull-right">
      <li><%= link_to '新規登録', new_event_path,'data-no-turbolink' => true%></li>
      <li><%= link_to '情報一覧', events_path, 'data-no-turbolink' => true%></li>
      <li><%= link_to 'お問い合わせ', 'https://twitter.com/applied_w'%></li>
      <li><%= link_to 'トップに戻る', 'https://twitter.com/applied_w'%></li>
    </ul>
</li>
</ul>
</div>

<div class="container center-block new">
  <h1> Add New Info </h1>
  <%= render 'form' %>
  <%= link_to 'Back', events_path, 'data-no-turbolink' => true, :class => "back"%>
</div>

app/views/events/show.html.erb
<div class="show">
  <p id="notice">
    <%= notice %>
  </p>
  <div class="event">
    <div class="event-item">
      <div class="event-item-label">
        Name
      </div>
      <div class="event-item-content">
        <%= @event.name %>
      </div>
    </div>

  <div class="event-item">
    <div class="event-item-label">
      Deadline
    </div>
    <div class="event-item-content"> 
      <%= @event.deadline %>
    </div>
  </div>

  <div class="event-item">
    <div class="event-item-label">
      Place
    </div>
    <div class="event-item-content">
      <%= @event.place %>
    </div>
  </div>

  <div class="event-item">
    <div class="event-item-label">
      Comment
    </div>
    <% if @event.comment.present? %>
      <div class="event-item-content">
        <%= @event.comment %>
      </div>
    <% else %>
      <div class="event-item-content">
        特にありません
      </div>
    <% end %>
  </div>
</div>

<div class="board">
  <h4>掲示板</h4>
  <% if @event.microposts.size > 2%>
  <% @event.microposts.each.with_index(1) do |micropost,index| %>
  <div class="board-item">
  <div class="board_info"><%= index %>: <%= micropost.editor %> : <%= micropost.created_at%> </div>
  <div class="board_content"><%= micropost.content %></div>
</div>
  <% end %>
  <% end %>
</div>


<%= form_for(@micropost) do |f| %>
  <div class="field form-group">
    <%= f.label '名前',:class => "control-label" %>
    <div class="form-field">
      <%= f.text_field :editor, :class => "form-control" %>
    </div>
  </div>


  <div class="field form-group">
    <%= f.label 'コメント',:class => "control-label" %>
    <div class="form-field">
      <%= f.text_area :content, :class => "form-control" %>
    </div>
  </div>


  <div class="align-center">
     <%= f.submit "送信", :class => "button"%>
  </div>
<% end %>
<div class = "back-button">
<%= link_to 'Back', events_path, 'data-no-turbolink' => true %>
</div>
</div>

app/views/events/show_smart_phone.html.erb
<%= render 'navi'%>
<div class="show">
<p id="notice"><%= notice %></p>
<div class="event">
<div class="event-item">
  <div class="event-item-label">Name</div>
  <div class="event-item-content"><%= @event.name %></div>
</div>

<div class="event-item">
  <div class="event-item-label">Deadline</div>
  <div class="event-item-content"><%= @event.deadline %></div>
</div>

<div class="event-item">
  <div class="event-item-label">Place</div>
  <div class="event-item-content"><%= @event.place %></div>
</div>

<div class="event-item">
  <div class="event-item-label">Comment</div>
  <% if @event.comment.present? %>
    <div class="event-item-content"><%= @event.comment %></div>
  <% else %>
    <div class="event-item-content">特にありません</div>
  <% end %>
</div>

<div class="board">
	<h4>掲示板</h4>
  <% if @event.microposts.size > 2%>
	<% @event.microposts.each.with_index(1) do |micropost,index| %>
  <div class="board-item">
  <div class="board_info"><%= index %>: <%= micropost.editor %> : <%= micropost.created_at%> </div>
	<div class="board_content"><%= micropost.content %></div>
</div>
  <% end %>
	<% end %>
</div>


<%= form_for(@micropost) do |f| %>
  <div class="field form-group">
    <%= f.label '名前',:class => "control-label" %>
    <div class="form-field">
      <%= f.text_field :editor, :class => "form-control" %>
    </div>
  </div>


  <div class="field form-group">
    <%= f.label 'コメント',:class => "control-label" %>
    <div class="form-field">
      <%= f.text_area :content, :class => "form-control" %>
    </div>
  </div>


  <div class="align-center">
     <%= f.submit "送信", :class => "button"%>
  </div>
<% end %>

<%= link_to 'Back', events_path, 'data-no-turbolink' => true %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppliedPhysics</title>
<meta name="google-site-verification" content="mJIjPkVYv__k3nEKZtTA9j8GAkm_bD2x4KJP5U8LjDI" />
 <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>
<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

  <div class="header">
    <div class="header-left">
      <%= link_to 'AppliedPhysics', root_path %>
    </div>
      <div class="header-right">
        <ul>
          <li class="selected" data-no-turbolink>
            <%= link_to '情報一覧',events_path %>
          </li>
          <li class="selected">
            <%= link_to '新規投稿', new_event_path %>
          </li>
          <li class="selected">
            <%= link_to 'お問い合わせ', 'https://twitter.com/applied_w'%>
          </li>
        </ul>
      </div>  
    </div>
    <%= yield %>
  
</body>
</html>

app/views/layouts/application_smart_phone.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppliedPhysics</title>
  <meta name="google-site-verification" content="mJIjPkVYv__k3nEKZtTA9j8GAkm_bD2x4KJP5U8LjDI" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "smart_phone/application", :media => "all" %>
  <meta name="viewport" content="width=device-width">
</head>

<body>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="title1">
  <p class="headline_sentence">
    次世代技術の芽と新しい物理をつくる
  </p>
  <h1 class="headline_title">
    応用物理学科
  </h1>
</div>


<div class="top-page-lp">
  <div class="content-report-lp contents-lp">
    <h2>今週のレポート</h2>
    <div class="content-lp">
      <% if @reports.present? %>
      <ul>
        <% @reports.each do |report| %>
          <li>
            <div class="content-lp_name">
              <%= report.name %>
            </div>
            <div class="content-lp_deadline">
              <%= report.deadline.month %>月<%= report.deadline.day %>日まで
            </div>
            <div class="content-lp_place">
              提出場所:<%= report.place %>
            </div>
          </li>
        <% end %>
      </ul>
        <% else %>
          <p>レポートはありません</p>
        <% end %>
    </div>
  </div>
  <div class="content-small_test-lp contents-lp">
    <h2>今週の小テスト</h2>
    <div class="content-lp">
      <% if @tests.present? %>
      <ul>
        <% @tests.each do |test| %>
          <li>
            <div class="content-lp_name">
              <%= test.name %>
            </div>
            <div class="content-lp_deadline">
              <%= test.deadline.month %>月<%= test.deadline.day %>日まで
            </div>
            <div class="content-lp_place">
              提出場所:<%= test.place %>
            </div>
          </li>
        <% end %>
      </ul>
        <% else %>
          <p>小テストはありません</p>
        <% end %>
    </div>
  </div>
  <div class="content-others-lp contents-lp">
    <h2>その他</h2>
    <div class="content-lp">
      <% if @others.present? %>
      <ul>
        <% @others.each do |other| %>
          <li>
            <div class="content-lp_name">
              <%= other.name %>
            </div>
            <div class="content-lp_deadline">
              <%= other.deadline.month %>月<%= other.deadline.day %>日まで
            </div>
            <div class="content-lp_place">
              提出場所:<%= other.place %>
            </div>
          </li>
        <% end %>
      </ul>
        <% else %>
          <p>その他の予定はありません</p>
        <% end %>
    </div>
  </div>
</div>

app/views/pages/index_smart_phone.html.erb
<%= render partial: "events/navi"%>
<div class="top-page">
	<div class="content-report contents">
		<h2>今週のレポート</h2>
		<div class="content">
		  <% if @reports.present? %>
			<ul>
	          <% @reports.each do |report| %>
	            <li>
		          <div class="content_name"><%= link_to report.name, report, 'data-no-turbolink' => true %></div>
		          <div class="content_deadline"><%= report.deadline.month %>月<%= report.deadline.day %>日まで</div>
	            </li>
	          <% end %>
	        </ul>
	      <% else %>
	      	<p>レポートはありません</p>
	      <% end %>
		</div>
	</div>
	<div class="content-small_test contents">
		<h2>今週の小テスト</h2>
		<div class="content">
		  <% if @tests.present? %>
			<ul>
	          <% @tests.each do |test| %>
	            <li>
		          <div class="content_name"><%= link_to test.name, test , 'data-no-turbolink' => true %></div>
		          <div class="content_deadline"><%= test.deadline.month %>月<%= test.deadline.day %>日まで</div>
	            </li>
	          <% end %>
	        </ul>
	      <% else %>
	      	<p>小テストはありません</p>
	      <% end %>
		</div>
	</div>
	<div class="content-others contents">
		<h2>その他</h2>
		<div class="content">
			<% if @others.present? %>
			<ul>
	          <% @others.each do |other| %>
	            <li>
		          <div class="content_name"><%= link_to other.name, other , 'data-no-turbolink' => true %></div>
		          <div class="content_deadline"><%= other.deadline.month %>月<%= other.deadline.day %>日まで</div>
	            </li>
	          <% end %>
	        </ul>
	      <% else %>
	      	<p>その他の予定はありません</p>
	      <% end %>
		</div>
	</div>
</div>